### PR TITLE
Make pixels per meter for line detector a loaded in parameter

### PR DESCRIPTION
**Pull request by aftersomemath**

### CODE REVIEW

**Comment by amiller27** [comment]
Tested?

**Comment by amiller27** [comment]
In that it produces that same results as before in the sim?

**Comment by aftersomemath** [comment]
No it segfaults on my machine and somethings wrong with the drone's stuff.

**Comment by amiller27** [comment]
Does it segfault without the changes in this PR?

**Comment by aftersomemath** [comment]
It doesn't segfault if no images are fed in so the part of the code I changed is fine.

**Comment by amiller27** [comment]
It doesn't run all of your code if no images are fed in.  I don't want to approve this until the segfaults are fixed and we can test this independently

**Comment by aftersomemath** [comment]
This has been tested, I got CUDA working on my machine.

**Review by amiller27 — APPROVED** [review]

**Pull request merged**
